---
kind: pipeline
type: docker
name: default

trigger:
  event:
  - push
  - tag

steps:
  - name: latex build
    image: nxzz/alpine-texlive-ja
    commands:
      - latexmk paper.tex
    when:
      event:
      - push
      - tag
      status:
      - success
  - name: github orphan
    image: bravissimolabs/alpine-git
    commands:
      - mv ./paper.pdf /tmp/paper.pdf
      - git config --global user.email "bot@drone"
      - git config --global user.name "bot"
      - git checkout --orphan pdf
      - git rm -rf .
      - mv /tmp/paper.pdf ./
      - git add -f paper.pdf
      - git commit -m "latest pdf"
      - git push -f origin pdf
    when:
      event:
      - push
      - tag
      status:
      - success
  - name: github release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: ./paper.pdf
    when:
      event:
      - tag
      status:
      - success
  - name: slack
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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    
    when:
      event:
      - push
      - tag
      status:
      - success
    channel: bachelor-thesis-log
    template: >
      {{#success build.status}}
        {{repo.owner}}/{{repo.name}} build {{build.number}} succeeded.
        https://github.com/{{repo.owner}}/{{repo.name}}/blob/pdf/paper.pdf
        {{build.link}}
      {{else}}
        build {{build.number}} failed.
        {{build.link}}
      {{/success}}