name: LaTeX PDF Build

on:
    push:
      branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: build pdf
              uses: ./
            - name: copy pdf
              run: |
                mkdir ./dist
                cp paper.pdf ./dist/
            - name: push pdf
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: pdf
                publish_dir: ./dist
                force_orphan: true
